package aufgabe4;

import java.awt.Color;

public class Textmodus {
    private static void show1(Color color1, Color color2, int row, int col) {
        // SWORD
        Console.setForeground(Color.GRAY);
        Console.gotoXY(col, row);
        Console.write("X");
        Console.gotoXY(col - 1, row - 1);
        Console.write("S");
        Console.gotoXY(col - 2, row - 2);
        Console.write("S");
        Console.gotoXY(col - 2, row - 3);
        Console.write("S");
        Console.setForeground(Color.DARK_GRAY);
        Console.gotoXY(col, row - 1);
        Console.write("Z");
        Console.gotoXY(col, row - 2);
        Console.write("Z");
        Console.gotoXY(col, row - 3);
        Console.write("Z");
        Console.gotoXY(col, row - 4);
        Console.write("Z");
        Console.setForeground(Color.GRAY);
        Console.gotoXY(col - 1, row - 4);
        Console.write("S");
        Console.gotoXY(col, row - 5);
        Console.write("X");
        Console.gotoXY(col - 1, row - 5);
        Console.write("<");
        Console.gotoXY(col + 1, row - 5);
        Console.write(">");
        Console.gotoXY(col, row - 6);
        Console.write("X");
        Console.gotoXY(col, row - 7);
        Console.write("X");
        Console.gotoXY(col, row - 8);
        Console.write("X");
        Console.gotoXY(col, row - 9);
        Console.write("X");
        Console.gotoXY(col, row - 10);
        Console.write("X");
        Console.gotoXY(col, row - 11);
        Console.write("x");
        Console.gotoXY(col, row - 12);
        Console.write("x");
        Console.gotoXY(col, row - 13);
        Console.write("x");
        Console.gotoXY(col, row - 14);
        Console.write("x");
        Console.gotoXY(col, row - 15);
        Console.write("x");
        Console.gotoXY(col, row - 16);
        Console.write("^");
        Console.gotoXY(col, row - 17);
        Console.write("^");
        Console.gotoXY(col, row - 18);
        Console.write("^");
        Console.gotoXY(col, row - 19);
        Console.write("^");

        // MAGIC
        Console.setForeground(color1);
        Console.gotoXY(col + 2, row - 19);
        Console.write("S");
        Console.gotoXY(col + 1, row - 18);
        Console.write("S");
        Console.gotoXY(col - 1, row - 16);
        Console.write("S");
        Console.gotoXY(col - 1, row - 15);
        Console.write("S");
        Console.gotoXY(col - 2, row - 14);
        Console.write("S");
        Console.gotoXY(col - 2, row - 13);
        Console.write("S");
        Console.gotoXY(col - 3, row - 12);
        Console.write("S");
        Console.gotoXY(col - 3, row - 11);
        Console.write("S");
        Console.gotoXY(col - 2, row - 10);
        Console.write("S");
        Console.gotoXY(col - 1, row - 9);
        Console.write("S");
        Console.gotoXY(col, row - 8);
        Console.write("S");
        Console.gotoXY(col + 1, row - 7);
        Console.write("S");
        Console.gotoXY(col + 2, row - 6);
        Console.write("S");

        Console.setForeground(color2);
        Console.gotoXY(col - 2, row - 19);
        Console.write("S");
        Console.gotoXY(col - 1, row - 18);
        Console.write("S");
        Console.gotoXY(col, row - 17);
        Console.write("S");
        Console.gotoXY(col + 1, row - 16);
        Console.write("S");
        Console.gotoXY(col + 1, row - 15);
        Console.write("S");
        Console.gotoXY(col + 2, row - 14);
        Console.write("S");
        Console.gotoXY(col + 2, row - 13);
        Console.write("S");
        Console.gotoXY(col + 3, row - 12);
        Console.write("S");
        Console.gotoXY(col + 3, row - 11);
        Console.write("S");
        Console.gotoXY(col + 2, row - 10);
        Console.write("S");
        Console.gotoXY(col + 1, row - 9);
        Console.write("S");
        Console.gotoXY(col - 1, row - 7);
        Console.write("S");
        Console.gotoXY(col - 2, row - 6);
        Console.write("S");
        Console.gotoXY(col, row + 1);
        Console.write("A");
        Console.gotoXY(col, row + 1);
    }
    
    private static void show2(Color color1, Color color2, int row, int col) {
        // SWORD
        Console.setForeground(Color.GRAY);
        Console.gotoXY(col, row - 2);
        Console.write("X");
        Console.setForeground(Color.DARK_GRAY);
        Console.gotoXY(col, row - 3);
        Console.write("Z");
        Console.gotoXY(col, row - 4);
        Console.write("Z");
        Console.setForeground(Color.LIGHT_GRAY);
        Console.gotoXY(col, row - 5);
        Console.write("X");
        Console.gotoXY(col - 1, row - 5);
        Console.write("X");
        Console.gotoXY(col + 1, row - 5);
        Console.write("X");
        Console.gotoXY(col, row - 6);
        Console.write("Z");
        Console.gotoXY(col, row - 7);
        Console.write("Z");
        Console.gotoXY(col, row - 8);
        Console.write("Z");
        Console.gotoXY(col, row - 9);
        Console.write("Z");
        Console.gotoXY(col, row - 10);
        Console.write("Z");
        Console.gotoXY(col, row - 11);
        Console.write("Z");
        Console.gotoXY(col, row - 12);
        Console.write("Z");
        Console.gotoXY(col, row - 13);
        Console.write("Z");
        Console.gotoXY(col, row - 14);
        Console.write("Z");
        Console.gotoXY(col, row - 15);
        Console.write("Z");
        Console.gotoXY(col, row - 16);
        Console.write("Z");
        Console.gotoXY(col, row - 17);
        Console.write("Z");
        Console.gotoXY(col, row - 18);
        Console.write("Z");
        Console.gotoXY(col, row - 19);
        Console.write("Z");

        // MAGIC
        Console.setForeground(color1);
        Console.gotoXY(col - 2, row - 13);
        Console.write("S");
        Console.gotoXY(col - 3, row - 12);
        Console.write("S");
        Console.gotoXY(col - 3, row - 11);
        Console.write("S");
        Console.gotoXY(col - 2, row - 10);
        Console.write("S");
        Console.gotoXY(col - 1, row - 9);
        Console.write("S");
        Console.gotoXY(col, row - 8);
        Console.write("S");
        Console.gotoXY(col + 1, row - 7);
        Console.write("S");
        Console.gotoXY(col + 2, row - 6);
        Console.write("S");

        Console.setForeground(color2);
        Console.gotoXY(col + 2, row - 13);
        Console.write("S");
        Console.gotoXY(col + 3, row - 12);
        Console.write("S");
        Console.gotoXY(col + 3, row - 11);
        Console.write("S");
        Console.gotoXY(col + 2, row - 10);
        Console.write("S");
        Console.gotoXY(col + 1, row - 9);
        Console.write("S");
        Console.gotoXY(col - 1, row - 7);
        Console.write("S");
        Console.gotoXY(col - 2, row - 6);
        Console.write("S");
        Console.gotoXY(col, row - 1);
        Console.write("A");
        Console.gotoXY(col, row - 1);
    }
    
    private static void show3(Color color1, Color color2, int row, int col) {
        // SWORD
        Console.setForeground(Color.WHITE);
        Console.gotoXY(col, row);
        Console.write("X");
        Console.gotoXY(col - 1, row - 1);
        Console.write("S");
        Console.gotoXY(col - 2, row - 2);
        Console.write("S");
        Console.gotoXY(col - 2, row - 3);
        Console.write("S");
        Console.setForeground(Color.LIGHT_GRAY);
        Console.gotoXY(col, row - 1);
        Console.write("Z");
        Console.gotoXY(col, row - 2);
        Console.write("Z");
        Console.gotoXY(col, row - 3);
        Console.write("Z");
        Console.gotoXY(col, row - 4);
        Console.write("Z");
        Console.setForeground(Color.WHITE);
        Console.gotoXY(col - 1, row - 4);
        Console.write("S");
        Console.gotoXY(col, row - 5);
        Console.write("X");
        Console.gotoXY(col - 1, row - 5);
        Console.write("<");
        Console.gotoXY(col + 1, row - 5);
        Console.write(">");
        Console.gotoXY(col, row - 6);
        Console.write("X");
        Console.gotoXY(col, row - 7);
        Console.write("X");
        Console.gotoXY(col, row - 8);
        Console.write("x");
        Console.gotoXY(col, row - 9);
        Console.write("x");
        Console.gotoXY(col, row - 10);
        Console.write("^");
        Console.gotoXY(col, row - 11);
        Console.write("^");
        Console.gotoXY(col, row - 12);
        Console.write("^");

        // MAGIC
        Console.setForeground(color1);
        Console.gotoXY(col + 2, row - 19);
        Console.write("S");
        Console.gotoXY(col + 1, row - 18);
        Console.write("S");
        Console.gotoXY(col - 1, row - 16);
        Console.write("S");
        Console.gotoXY(col - 1, row - 15);
        Console.write("S");
        Console.gotoXY(col - 2, row - 14);
        Console.write("S");

        Console.setForeground(color2);
        Console.gotoXY(col - 2, row - 19);
        Console.write("S");
        Console.gotoXY(col - 1, row - 18);
        Console.write("S");
        Console.gotoXY(col, row - 17);
        Console.write("S");
        Console.gotoXY(col + 1, row - 16);
        Console.write("S");
        Console.gotoXY(col + 1, row - 15);
        Console.write("S");
        Console.gotoXY(col + 2, row - 14);
        Console.write("S");
        Console.gotoXY(col, row + 1);
        Console.write("A");
        Console.gotoXY(col, row + 1);
    }

    public static void main(String[] args) {
        show1(Color.CYAN, Color.MAGENTA, 20, 10);
        show2(Color.ORANGE, Color.RED, 22, 40);
        show3(Color.GREEN, Color.YELLOW, 23, 70);
        show1(Color.BLUE, Color.CYAN, 20, 25);
        show2(Color.PINK, Color.ORANGE, 20, 55);
        show3(Color.BLUE, Color.CYAN, 20, 60);
        }
}
